# Generated by Django 4.2.3 on 2023-07-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shelter", "0002_alter_petowner_email_alter_petowner_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petowner",
            name="first_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="petowner",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
    ]
