# Generated by Django 4.2.3 on 2023-07-21 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shelter", "0003_alter_petowner_first_name_alter_petowner_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petowner",
            name="username",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^[a-z\\d_]+$")
                ],
            ),
        ),
    ]
