# Generated by Django 4.2.3 on 2023-07-21 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shelter", "0005_alter_petowner_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petowner",
            name="first_name",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The value must consist of A-z and a-z only",
                        regex="^[A-Za-z]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="petowner",
            name="last_name",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The value should consist of A-z and a-z only",
                        regex="^[A-Za-z]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="petowner",
            name="phone_number",
            field=models.CharField(
                max_length=63,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The value must consist of numbers and allows parentheses with spaces and +",
                        regex="^[\\d\\s()+]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="petowner",
            name="username",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The value must consist of a-z, digits and _ only",
                        regex="^[a-z\\d_]+$",
                    )
                ],
            ),
        ),
    ]
