# Generated by Django 4.2.3 on 2023-07-21 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shelter", "0006_alter_petowner_first_name_alter_petowner_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="last_vet_visit",
        ),
        migrations.AlterField(
            model_name="pet",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The value must consist of A-z and a-z only",
                        regex="^[A-Za-z]+$",
                    )
                ],
            ),
        ),
    ]
