# Generated by Django 4.2.3 on 2023-07-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shelter", "0007_remove_pet_last_vet_visit_alter_pet_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="type",
            name="name",
            field=models.CharField(
                choices=[("Dog", "Dog"), ("Cat", "Cat")], max_length=63, unique=True
            ),
        ),
    ]
