# Generated by Django 4.2.3 on 2023-07-23 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0012_alter_pet_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(default='unknown', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='The value must consist of A-z and a-z only', regex='^[\\sA-Za-z]+$')]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='The value must consist of A-z and a-z only', regex='^[\\sA-Za-z]+$')]),
        ),
    ]
