# Generated by Django 4.0.10 on 2023-07-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0013_alter_breed_name_alter_pet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
